### ISSUE TITLE
IntelliJ 2021.3 support

### ISSUE THREAD

**Issue by andynameistaken** [gnakic/earthsong-intellij-theme#2]
Hi,
Could you add support to 2021.3 version of JetBrains tools?

**Comment by gnakic** [comment]
> Hi, Could you add support to 2021.3 version of JetBrains tools?

Hey, sure! I'll put it on Jetbrains review sometime this week, and close the ticket once it's live.

**Comment by andynameistaken** [comment]
Cool, thanks for the theme - it's my favourite, I left you 5 stars on their site :)

**Comment by gnakic** [comment]
Thanks @andynameistaken! Much appreciated :) I'm closing the issue since 2021.3 should be live now.
Feel free to offer suggestions and open new issues at any time.
